### PR TITLE
Finished exercises 07, 08, 09

### PR DESCRIPTION
**Pull request by AnvarArt**

### CODE REVIEW

**Review by emperorliu — APPROVED** [review]

**Comment by emperorliu** [comment]
@AnvarArt 

I approved but your book title solution is a bit verbose. See my solution for it:

```
class Book
  attr_accessor :title

  def title=(name)
    exceptions = ["the", "a", "an", "and", "in", "of"]
    name[0] = name[0].upcase
    name = name.split.each do |word|
      word[0] = word[0].upcase unless exceptions.include?(word) 
    end
    @title = name.join(" ")
  end
end
```

It's much easier to iterate through the name and upcase each word, with the exception for certain words found in ["the", "a", "an", "and", "in", "of"].

**Comment by emperorliu** [comment]
Regarding my solution above, `unless` is a pretty useful conditional that is the opposite of `if`: https://www.tutorialspoint.com/ruby/ruby_if_else.htm

**Comment by emperorliu** [comment]
@AnvarArt 
The `include` method is useful for the future as well.

How to use include as a method on string: https://apidock.com/ruby/String/include%3F
How to use include as a method on an array: https://apidock.com/ruby/Array/include%3F

**Comment by AnvarArt** [comment]
@emperorliu Thanks for the review
Will refactor code for the book title solution with my next PR

**Pull request merged**
